version: '3.4'
services:
  db:
    image: 'mysql:5.7'
    container_name: db
    env_file:
      - ./.env
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
      MYSQL_USER: '${DATABASE_USERNAME}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
    volumes:
      - './.docker/data/db:/var/lib/mysql'

  node:
    build:
      context: .
    container_name: remind
    environment:
      PORT: 3000
    depends_on:
      - db
    links:
      - db
    volumes:
      - '.:/app'
      - './.docker/node_modules:/node_modules'

  web:
    image: 'nginx:1.20-alpine'
    container_name: webserver
    ports:
      - '3000:80'
    depends_on:
      - node
    links:
      - node
    volumes:
      - './default.nginx:/etc/nginx/conf.d/default.conf'
